openapi: 3.0.0
info:
  title: "Bulk API"
  version: 2.0.0
  description: "The API for performing bulk uploads"
tags:
  - name: "Upload"
servers:
  - url: /bulk/{stateAbbr}/v2
    variables:
      stateAbbr:
        default: none
        description: Lowercase two-letter postal code abbreviation
paths:
  '/upload/{filename}':
    $ref: '../../etl/docs/openapi/upload.yaml'
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
