openapi: 3.0.0
info:
  title: "Duplicate Participation API"
  version: 1.0.0
  description: "The API for the Duplicate Participation system where matching and lookups will occur"
servers:
  - url: "/v1"
paths:
  /query:
    $ref: '../../match/docs/openapi/orchestrator/query.yaml'
  /lookup_ids/{id}:
    $ref: '../../match/docs/openapi/lookup/id.yaml'
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
